---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgC7o6PX21JWZ0MtpeQ3WhXX/WJVkBNU1K6KAMssiUdcNaEBZgYDVda3ZzME3XHcRYJvGaT8pUlkdDMq/prwfEUDVwQSdPsQ3bLNLjA385Cldf2Z+nvfztIF+Fi1r7lOlc1Ys6nxt6rcFDDEVSJ7bqryKAuZU6koKav74TXZk869gnCAOL4NiKMAw7jS5Zbw8XstpdiZHz9/CNVmt36+BnVz3ieDsyyoT6IVGyjpohPl063uYVxAdIZ4LMKspl/cjlYvh0sGKWdePTnqoKjKG4Kg03vftZ7KaZD0MF30tr7HcPkvf9+dBgCDAxjhAtPcSS25eNC279nNEoYQFd31+BuwhIYyPZrcV/D3F/+vIcHIchR+aGjUOw3pbjtnxINNwwIV8e2svPrKihoHnbUyjDe/h9xB1My127EjFtkNkdgob/b/P0moxp+FL948aLI70rvnCupoar3CKn5oM+OzBpf6aS8UT5FvD8bXRBaqNhbfx83V6EozzHWRpoRYfWBp69ROXLkawQ+ooVfv8FLyfOazMtB9R5AMduEouxg8oLEJubJaBsGqrEtvsnK5C5ETiHYQr9xCMEQ/c8UZRduuc3P8KZOJAt4y3dBi9ZsaNuAKk9xwV6GTrYEz+moRxw6Pm11hpglpGdZEP5q1vLf6bm5Z/xOsag9gni3+joWB20HfBn4OApb/iTmGDs//nrlKgjk0jXYl3ZCcN77rtws=
    admin-user: AgCd9htRNfbRS9ak3DQ93R5Z3qZIB+dJBUylr/zmCPsGb/bzsAqhNjN/nO5qoxb1t2wc0tXBXjPImiUZDR8BOsHT9rpqa0i5/1CMMxtt8VPCVJbWWc4ZZ7PqgOVLYMQQBu0XC14rFsBndQYH8j8I6uhamEoUVTbCaEdr0mFrD0F9GURws22DEVOIZErb4e1Oq9arRRhEZ69ZemhL4kXFJgSPQ7L5L528YueO2eS0BqY4OpKUoegjvVg4NC60/SzDfwgpMCbRwo/O1E7pBfskm3EwrPRueR848Rufcx1BqPyjjDIZnZMuvKig9ht4wL514kTqdcrBsg4lv02bIc6orI8SvPwhYY2ajIQnB7sdlyq4GK/TaQAzPlbAcXFlcqEOTrgmEXtXintD5ciE7vocny1PunMCAvkh41ldS4icGDYigTy+ZO8q61HoprXQhFo4n8omeW7rt5WjaBeQR0uxY30pl6ROoLpRt9B2u1JiQ9p2mY+LGmHiuAr3W+gzIhm4742186XOAXEHQ2urebkUhczRH/we5JF4UUd31sVPUWfRU2LY8udPo+RHJw08YzE2VbWbvjDDQ8HLCvLeQTm8o5LOsa8Eqn6yVTKW0EPhBwGDB+zwFf3JsMffW28bfnH942wv+avAw7rHnCsQJBh+Jo9L504LA869BunxIvHA5obmfJ0IMrTttSidxntiZ2dbf1TjZfY7dw==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
