---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: production
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB+WDVUltXkSAf8RRJ5AMK93GUDEfjLI8wXXIZGWna+Mh0QSHJQXgS/Pm1LJj+ccXPMYvTl0XJKhN/XsyNxu/3v4m8Z8E/YHuBhKruzN/KBjeKvLpxmGxFaONZiAeOnZlchKlOrcwkcDEAPJEkeYmqLB3KvIxg9aC0GfE16wvcdJrxaIb1cdL/FrMfalHtuA4v5b5lXlRBbYYeTP5BuznuPJGH3pRD4TTD7Lsdj5M4zgR8Gxk8WvoVYuO3O0VO+dDNUOhR9OuB0YJlw1wie5YAFXPqQtwW8JB+dX4WVJpTxhjgoNAojjYxkmRnXPZOrcHBxc+RsiNM1DNBUqRmqrT3sT1oTyO7nQIAFBpmlpwKfuJsneBMMwfBQUUvWilRBGwe5FQ/0+YTJFBs1ogstral+apWinrGG0MPe4Ytptr/TGip+A8BuUdMfB2tz/iBT2TvMH0/XgwmWpNdBqgzzY6rD3rbrxRLH3mXUXmM5vPKBnnU7lKJQr9VHp8SYqZAwGMYZhgQxKJSyI1cP7uqX8xQspVGyCgCwhWCFlphiOH8Niog0VCesMWVAEx1RtE6MmXNsa/Us9hh/8fEbZyLGuM5eI1g2vDxRpogkW6LepvrU/Pwp5YzP4ulY1oxiuC1PZLEbWuPfMaSdgXkqXaLghHO69S4IATtTPQRZC8nHEiU0KVlywTXfvEYNWa1IiIwFfk60ZTvbhpZXPK6lwwgPYywegZ4=
  template:
    metadata:
      name: postgres-secret
      namespace: production
    type: Opaque
