---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: production
spec:
  encryptedData:
    ADMIN_SECRET: AgBPRRcR10rG1iYFlcXZE8D8Gkag/NiKw5BKEcaaMZADHINer0vctp+U0rEGXVTq76PAb9IFjrzTwZv7QqC3GyIQltv3frM+xAPenA8JR8FKWa7lGXxyakNnNwScAJfrH6G5T5nIXeO/x/pqLqhj0cKDvh9N5iZkgLW8C3pLJPy8f2j3DKl0niJRbb9FOgHnAcu3QfeYwkyVCho5OeSwun5k83c1dT2KLkPizPuX4CTaVgTYg2g9AyMuwXwPTRGWjN574MA+yAxErUht/QSeepsVr6nhvpKoK/85+Gmq27LmDUdNBmBrh5rypOKS2q/JeM0VSGclzC0yoIH6R0OhDvTGahuplPk+Sf/T4jit/TZ5y5OG6ilWVC9CWJOgp4Mv3/iR4gQXxFkBCEcVwIeHhFdm+uW1QAnQAVxRyhA7gIJrXfBKz8UI2CWrOVNKahrOnXGk5NdRr5mQd/HLS4WTzlo1G+H4RYWJWd4mNtM56s92IjdZCHK6HNT2TTWnQpgeNS04vBNcPs7+t+h9iYYvWvC3+ICl6SiPN4IXW3/5aTMyD4O80EY1+pPIAnFbzEgxjI2ReAwEEPUEFZotGZXQrJ431FtbsVUS9541TOlRtDz/415MFnN60GTctMo2SQFc5KXVM9ZbRNcSUM0aF7HFDU+O48t7kgLj7Dmv7EzX+2GhLHM2OXB/FL9rfNxhY75pTSDqiVMnpf5wtp2LRrht0Gv/ryygc8Lpa9L2Ds45INHLC1q56WKO9iquNcsa
  template:
    metadata:
      name: admin-secret
      namespace: production
