---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-secret
  namespace: production
spec:
  encryptedData:
    ADMIN_SECRET: AgA+lSe9MuSMGgCWZSFFsVAdTk4qK2nuzVKgTz9gHOfsedCLG0t3NhLpU54QG8dQ2Q0KInS5U5gb1GpMVfSlzEmjnbnAn8MRu1eaKJUVnrZUkvoB/JWjC4DSJx2S97tTmMIQNNVAFoQW2KiouYaLYcjZNhxQS6niTR9xD2S/xQ8t6nczVdVCZDknzhPNQ8dW7MRTxXScUpmdhndgs4KSkAkDjAWON+3aS2ADfHosy4BQcxfSKH9kPeZh0wJ2fVD/bmfKbZXBNnJVS4YAeVoYJEujUKwLyaznn6oAbVbFoO1ED0iWdrw7Qcq9LOSmJPlqmRztENYi81ogBugtLid7JyjRgguPCP3zdStuLIMAfIuE1+oz3cj311ezPXlLz2cmwVrp1haW+xmdFHUJHXDbL2qJJE3K18U+s+jK7ctZdL8FY9yZunoqjHZnssSOWmwpWnStMb+cWw2em36c8xhbH87vxugIvnMSno24JL10p55oPb6JnMluY7wvHz63VXtWvXLsR6FDI1vULwKvV9Sgna0S7MOZ3OXd/grb61FSIpMLwE3SNKdifWjqU/T2HG6FC7XwthI/m8aG3HAoM06/WkEDO7Hd1DztZ9jQm1C/2wqz0iHBwaBO5i8RayActmlysNdhTR/j/qpVdJUnPeRVUDROAM30/RV5ficrcpDEa2MT7msxLaoA+YVkEdlKYK3fVnfVK4MhzlAZPWi19JTRJ8z7gJYmkqrRhvH4Udr/koafmTJG1lG6Ir3jCQaF
  template:
    metadata:
      creationTimestamp: null
      name: admin-secret
      namespace: production
