---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    CREDENTIAL_PEPPER: AgBWzAnsa/2OjRbvxV5CasXSprWmxZfjnSbywxipw6apKUSkUKez9lwIhtIJDbqZP8klFIAfmyIkaKfCXnrULK9zTHlIkdvUYQ0YaOJLoTsKXwVIQa7R+sg34/vSI6hxdckB+JOLgTuiIOABUQrqEfx1dJzwsERhieuG6iZ7FzKTtV740xGsBpdrcRaKSsUl1hD/x3eO+jxT87OvW5JCznvZXe4vVkUjvWEuaysOOnb1mXvbc5uB4Hqn/zr4uzetgLU1H7QefR8Jptu47UUB03LC5uBBmc89beNWXYI321GmQzfPNEfxxHnFzpocuBcjPwHkrE01uuJdGDF9O7Z7uf/KbnTj2KqnLxpSBoQTBD/D8IivEElxl4/y4EqEOP54BO8TZC4WbyoXBiJ8n6zoBFRJEsrZsS4gq8BL5dDlgQ4R0MpWD1kEIXWEBJcBeG31dBFo3Rh7lmmWyPLsQCy3OBooIMKNWLNNrC06G8lDwMgm6slGmF9fTcbhMuUYExt251hFMFyEUeJktxYhdYAXjvDC3ufR/SDw6wQJOm9FjEKGwVBkHCLhCmjInGymvBVJPr7Nr+z2kqVK1x2lBQqBjxU144Bs1JuwlHt46sDwyX8edrdkapyV6jzC5+fNSTZOzx7ZNLnsONhJH0+Ctyf8Yn72xQqvlDuKGtA5rkHjvyrKxcxA/v+9ZtSCjdpSeXk40J3QoUaQZIZCs6aV7u4LAeAwawFrcvmWpOQ97J6W
    ENROLLMENT_SECRET: AgAjGzjneObACOMMrqHeCoVdPTBMbkrlyNatT+nfv4pCWm6R9bRWwgQIQZS6FKv7/WdDlG0pS+SHAgg3NjDneA//1O1HJOcgm/jWviEv3nfyZTDFassojy2Bi4t8ySw1jwZXztr+T5Aoeyk4Ght24V6cWx0p0HHmYikzz+2zY8Z1YnkVmSMZw8yWRHGu0KR3WLlnDX7v02dR2VJWg8B8WknRPCqYG/Q996Z4KPShVVtIgb9kKhSGRRy55TPqsGzyCP/AHa7j+PSl5XAQ8ctMZncKUkm9o33ezcyhib/60D0oglGk3ivwUhKYZPscuD4pnzQX8qq8Qn0QJTJlm4s01obI9Rn6ZomKM36++g8W/zqhPAFcXIKpgZqkSe/O2ddCZlgM+Qfa3sdOzDs4v9qNV+b5u2xI31PIGXZtRYG0h1G444oqSs9eg3NzmIUDVdOf3HAy7Jlh00iHcbn+y9v0wAqB6Dv36IzBuEDV8r3aSlOlK4X249t/xX6vIrKa5nR//uKQhH9o4u/oZgUOWDXt5uq5OvaRjLaFhXm9DGvUGDovUK0F4NfwCtC7mdH8vFUK612bhpp7+G/bROnLUt8YpEJz4P7yN/EL6HWeJZzeA3k4as8PdGKpKOVJtM+bT7thH0Pi2+VUb3OWWYf5OjAZL765b+TZZ1R7xN7qCst88e0cZM42bq209P3C/uS2YfrBq2qg5A6HDgwxHnj5mUVzNiiYsD5pF8G/MlQivhw9
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
