---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  encryptedData:
    CREDENTIAL_PEPPER: AgBqDeQ6+zrYf+FK/ze9vXYCiR4lZBRU5VSCzfGR6y/awvlqBMTSnA2kPb76+PZLrscwgBd0YevxQnUb2sCUI91XVt4/lq8ck5+YAkPCQXm0MUSReXmWx8TNpxEYpfwTgLeNpxXt3t8jIhcegZSR+vv05eUkGd1rp1gtbX7kJWK+6xhKwOOY9uwIELOCylA5iFmVJzSO6psRNsRx7M+wDQQqOyZHvAq7x4RySc7SHcVPZhuRK/bLP/p1w8OL+hV8JLGIyNb6w3xBfqMgICcioL52M4wprVUzUEFkSdipAW1LpOi0e4t5Sc+7XgshFCp1xnFlP82b/RIFfkzgfokS7VbSAhpSvONIKW1LZcq2o1ndsA32MCH0uKdQ7NOdk49WWcCiaij5A77PqdUmuM/KDg+fel1brQCygMEOdIumPlWlM9Ue8lfUaVAeeG2MNtykcmedDfS4JUdak1eGTr4FOpikkF7viFqVa6pZiSIHgHcrSGMXN5uONNlcNXmXxlZVEVliaj2xmYir8CV9l5ZZs6CN+gkQDvgivAVqkB+qsTd9I+UcdmlA5kAj0dfLNBfXdHquTR1N6rw09129Jd8xBlDzfCTLvrPp34hqCBwn23uFFO+U9Qp/QEmPPkGe99T4GC9kTLOp770CleQMyfHjPHuUrZYBgWtFHXpwVqipGuaCVa38yfQLej1KoTqcBJ85UgtJU98DP28k9Im4Ujar9JU1rIfJBOqYLuqLhbtZ
    ENROLLMENT_SECRET: AgAak15sAZjfIN2p/TqoaAvst11/MndmQsZ2v/UNknnxq6N71RTH+6jujtYXlMuNE5uR+CtBOKjs6dm8S1SUPQNw44iGVylT2MTZZskSBGqr3ONC9d7c/myyfxNbxm1ZtumcDcloI5w+k2MvlQLx0AeUGAT/cF5hvdM3rokWMzrfpLO+1K5+04uU4W1zl1AIjfQuufEc2azNdZkGfd8j4rxPheKHf79xf8wIMMCpL6aOv8215DvaPU8MkHHf7Ch/92W1qUPEm42ULDVCTKrnFu6BHtwKjIJuqfQRw0/09FagsbsYzCH8bHRns9HUiVAKzrVitzGvEpXacOtL8bhG2E/qAPf51AWsKfpAeHPxzclx0pHSfGqk2IVcQYgbVY6xaObYjhlwoPPZnOl7DfEeFRC0sil4mnUVQnIiTHW86L7JS63/J5AfwXPdK5ODs7oRqnxg1cWD9Mt3zfJdgG7tSaoHn5PnrxZpGB2E2qWW5r/YyKi07EXNGvYchmX4yQsc+TsAbvwYxYuRm5zkBrTvy8wMb+v07e/QBb/w7+zdGBV3DDRlfnJ58m2wXpiiS8+Mvvt6CeD+eM2YHGaF/aoamddmq0oCfkIJ4dyEuhjsdkWdBpls98Z7y7tWpRk5AVQqq88C5mD6MuUke3fjTmJ6vwH0LH7Q6YncL6oYAT1IT+8etEqrqsYmZSTyxWQO9F/qyqAUch7bSr/ae+Phl60bIuxIATWQvvYhuwnJ5jIfOEfvjNbhqqqMA4uY+mDp
  template:
    metadata:
      name: app-secrets
      namespace: production
    type: Opaque
