---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-secret
  namespace: staging
spec:
  encryptedData:
    ADMIN_SECRET: AgCPBqry98gw/IqquBJyRc2qG0gDG02pgbJ+aHeCsKgdn8N1b/4Ej4Ht4KOgjhsRKHd+gVggVjpmVb0/z18k2+jg+EClH8bs4g7xyMlMikpm5kIb+SS7p3Nf4p9Rn//spSAycsiZ9wJo9S/IOXTU8T0hOh91qmdJwN6NoI1Ka+YWMdb/oFwodFaOFnrba14yeRRdUFOYZEVKdgDQdo6R4XN5D8kxsKQWFV94A4tinrSrjakx4utn0MctkcDlqDZaJTFdA2ATrluBw7ko3kO8aF5a83GhoTgiMpxQgjC6V2LeVnvtIqX0OdPzTLjUOL67rVQCstdPCjwtRH43kmpcoTFznxy8907TNlzCEJsGNEUAWtSfPd2XV3QnhXME/fnS6SC6iEvfF9MF7d1ECoe5Z4ht1nY3aODN1hnp2MDR7V1ipx5dr3gkhYMlW2szL0kkkgHs4jycbVW/p7ULLegtWhWCBM8jewmWFS2FFu7j1gyoZ6VGRrEFcLBxrJujNkLtazXeHjOA2P6eiofo0sAWpOgF20xV8VXLophjW8vi6UAbrPDaWs031j1LCUUOX0i2hzZJi9tfxBnr+78ltCn8x45YZrxNcUrRpqKhJHtRClEZbj8jidxvmrSbvyA6yonVtxJJ58ddgxtSveFl3ebrwQS/PvIUuRUDIEg3wvPzO+zwfFv6IpyE7gTF1dyTBy5g7PBVHLbYpUU3jyoNzVKp8yWqclQkXUZxqYt4Trh5apTFBpj5Tag/FWPb4AEh
  template:
    metadata:
      creationTimestamp: null
      name: admin-secret
      namespace: staging
