---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  encryptedData:
    CREDENTIAL_PEPPER: AgBH755HooaPe2XZUgk6Kyaq25y6AIKAvXWo4SAmMfe+mNkLPA00XXi6NMQf7d5Mvw04Sms5qY38vC80fTbnTOwHNHIKZvqCzNAc9pkd3O7rf/NHbdg8iQGo7DhBvqZyg3Xl7yktA4vGy5CVklhyZUu0gX+OfpaGJOSZOzVyLPndpWO61mUA19FBSdEvoMqTzhEp/+2+0q6uh7DmxhvC076tQsVrGZbvzLZ4HOz/kwdQq71Xv1V6rkIfjNoPG+teRKRpYjjMLRNjenlckkIafGDO7ApjT72LkJ68oaJLjFtqnoz2GxMIJUD9mBdyb3+Ua7JjTM1Hk8Acl/pMuVVserzvNaolE7aQlwKEAaP8riuELusB3t6WTGHA8CelRy7WEq7Yo7/TUcsIFoQeZ5hcwEJyZ4XnSo2awzCM5MwkeEHNrnPY1frT3lszdkixkUDn0IK0xT/vgvQLHqMCNrQbA+ysdgCec/CTNxsM8RdmEM0CRkPsl3z8IDXXygVhtRgOufg28cjaA6AGtNS27T9ETIt9C8kD94R5lZ6tq5ZpP+IqxDqo88JHizzt7yuFpyt5f0rqpqIEfyjCvxF2kzyEFSEGN5CopdGf+malgIIkbWnevzbkausNZ4F6WXXj13ygKlECxoTnLCSAFCHynekLlXcHZ91U85xezOrgjrcM87HT/9HoCV8reMotZ5ope80OcdV+Z8ptVd2NldBBLiHaEjFoBY+ADOYTFYlvrry+
    ENROLLMENT_SECRET: AgA0E/K4lK978JNY8+fEu0xKxCNYSoj0ma+37a3MKlA3xMQK9XeXkdUmgF25f3zqEjUG+evPeqorAthSfpVwC2L1vrHH0Yf3MDti1khe/TwOzZFCDE/odm/KB/ZjmPBin5pvpKnUPvTHIxpFXpEm40Nj4UqJtRghWGVUlQTv7bessmLJayhYUsvRjYuvCQgnZKEqILekWi+Q/Uun7dGLNMxnR4AC40cMkBx0zZHiPJoezU9ijiWGN15dyBuoFtoI6+CtwTcmNJ31S8hzTqtemCnzvQZeL+FWFS2cJavZdybCoKNHIJJI0+w3kZcdN793olwn9Xsh53TZafBYKvV2t2Ldp9fxa9Ji/Fe/idnYU8w9IMAC/iIQ/r43SiTM/N4fyKfWN40ZIWfULJREAN7Dh38DQA2VWL9kcKc343UIWjHIHCf3vzUxHOZUI9Pj/eFRybqnxVFVB62wTTBaZTiy6VfETUmHhmrHjyRfobZtsHuSgtZzHTyUGWAaINb6THbxaqlTh0J6yyj9lgyAa/D05vxMuPmoDAjgj99/PES8MhCL/0bTwmAeGPSE7dUd/zABwhe8wWXUkxR1YgchKPJWuWMXgd2SW3gLyEmcu6Zg3T1wh58xhGt4LdwPTkRtCHOgPEzM2Xjw0UWOwZmCY2dj08RovBUgC1VpXEoBq+xuNT0X9O522Uds3hJPUBWI4FRFqonBU7LtgfBQ3hYFzbgAzjTMfwmY8jQNhg0fkRoVWEcurG9qrcahGsSQb4mk
  template:
    metadata:
      name: app-secrets
      namespace: staging
    type: Opaque
