---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: staging
spec:
  encryptedData:
    ADMIN_SECRET: AgCRjhywYfiWVlztPRzcGzP8uExR4b2y5u8/MzKUpdzntKhpkOgE9TbNUlPf54V3KXsAGCi//NWq8zTljmQ/9YRK8W1dbqTi+aauKhNUuMGN+UvveQgMgqpPGC4N6MgkKPdw9SiV3ZMfzxBGgqEjvLQAffQy6k3xGE9uMpT5zUMVctmaWdhjji5s6DnZDFGt7Slp0jPivsuOj66VL83dwo3sbv8tk05X85XUCvzFICApYCPpe3BQ0Qb0ZeKwHAtTrVMXRKhhrMwwhZ6WOpn4W4aPZpYRSlx9NMGL/+GKXi5wMSC+C33fDYWe5doJ6Us1DN/r5LtA2eisiPTFx5ZJRsAcX3aX9JL6SAeTceLmrrLtk6z0cflJwrZpw7JEFUJMqyLNYdXgKTDI03vaXxW2tCyEPq4lpzZDxVwKHUgHA2slMw3iH7g9IaUXAS3lS4HWLLcRhJKPaH21XksfMNq1su806nVJ+MOD4WGpH+m+ZjJV8Ivfl95ZpWGQvY8dfY+/8hB8BeUmhkT+TNhapihX9Gjyd4fpVX3lnCuV6+/PgqopWvQk0fI9JlSkzDwElgPF/mF9OfjpQqGDgyg69TJCMIH8/8EMxBpRpK4uMPdXvQ/kvCB+l5Rdi0ifPMu9EWpYFRXux64zKyzW7tOi+IvvZlWQSpv/Ew3DmlREdSwgJvMjWgFU449nJ914GQooD5FEHTrZ2dqIM00Fa7AUQK7JxWwKGLNzto6mUCwpkJ45jLIViFZ2IbCxDafyIG3Q
  template:
    metadata:
      name: admin-secret
      namespace: staging
