---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCpnRaPMGBDe4SIKU+nPBsTCfOUqdrc5H2hD00BHMrOpIp6oSxmeZoyusg9MwHIOxPzE+/KrE08iHNoVR7G9MIzHMJVdUTZ/6h9CzZNiBTAiPZHfJ1U5JAPds9aoEiAfRAI9U0aCURwgQgyexOr+SG5yYAg+wa/Kt0OvgiGY/MgxVnsF32aBhT8Mcfs0kkASjnJXie+UkD2t3HNtQ9j7eKsOHte+hRDgJYVRItuqOcnyYYiYrKCYiRvxP2RvUG3ksKHFNAEi94rjgZNzxBv/RaLN2D6BVWEsGFheYOR2VT5RRMeKBcQ4bFZddb7I4bThfxJii1DjNIvwrIowa11db3rBrWXwS9UqkxiYaLmR3iv0ZpZQw5OjCSg4W4qHP3VdepEIj61shVN1CRq5RiqIvofDZvllQhRhhgLJPjUno8RKyjabSaHOsuiQMzyuc1OHWPPlQjvHeIQr+TlPpwCo59bxtbVadiQc6E5vlQ/ifmfNnHXb505b7jq43asoGUiifqYAuSHfSWU3AZtSTJKLF/61fEiO47096wYM5JSSLpwP+KG+HC/BixE6R5w/b/mD6A8PuLlojCxqAO7urnSDVqjjjqviVLnFxlUTMJOiy1H4O84jUhLzG4zdlBux+fe1a+1pGp2TEZqCBIK3GuFCEMfw3Anc2KLGa8zD0W1RmF0Mq3Oa8K4StoehJR13vunhRfe6sYKmli6c+3y/mxjjMCuQqw=
  template:
    metadata:
      name: postgres-secret
      namespace: staging
    type: Opaque
