---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: staging
spec:
  encryptedData:
    CREDENTIAL_PEPPER: AgCLN3c8eyai9CjMdY9EdVBMIBxFazYoZmK5ZEj4Jmg7PeY5jvBCpu80LQpt+z23id2cLsfya5cjU9DxKLqw+J1kAdBmoATRg+97u7oF2abEWdBOsOSkZA0UxlkiZWl6C/Gw+OhwTfKrlDNOwhXzIWp9CuHfhAFGeduxPaUeugGDfTE/Dm8PQ1+O0Al49IUOTbyIBiVvMbYVqB+xU9VR6C9ktU6NPmcBFzXboX2MlHwoO3E0eknYjj/a++xxrvJpbY6GP6HhoqjmGme1XlEELFojdngo77YpBxzC4CbDgOV6OGGZnosxM7EIuoRnONIyN8gktYXWZbvqV94zX85+d/mzgk23I12ao6pAPEFEruCiCW0FgPZb8iWmxej8IAAbqrenR9jcC/OtizIYA6RkXX3JJglJyBJltAFqkIZtBaegHNBBARKPRADQCZPPKKjsxs8f8dQ+ahSEL0m38YJwqkdfTXfA3JzsW1esLyeu8YXJWGm9xAI3NV4i0D8d/iPbKl9JKCG3SQjdTqMtNOrnWBojrAEfC1GbOQDqV2FhqIANq4hsffxKFM3mFND/nAJgVh3j3UOnRFyvZwr6XFgWl2vnBhHHZQEpRZdcgw/RhBs7vf+ViYuJejkif56dtCnQi6g/62vY+sjClvRw+wRl3P6r6+zWtcWv+c0Q5rsOeJR8VdciQmtEb42bUsFctLWML6SxtzjRNvhHqVlnynQd3s8bE+OMp6HnDJzH5QVX
    ENROLLMENT_SECRET: AgB6HhHObvTuabawrrPrcXxK9nCYziqth1UGumgWMCzPJOv24zJmPmZF6/4OMBxnwxIG/3EqyWJazCZ61cOef96hFYlPzdxCWz7e4j8XhPPZf9zPyRfYEI9Vok2S2C2EmX2nwtwxZ91U+nAV3E2uGWMO6rEmYZB29EA1Yd9G1xjJUF7l9Iz/v261zjcsKZLM4VdQFaLWJb1jCc5e6yVUjNFhjdfCnZPBjmeTvpZHFzQXfokc+52tukTAJ/FQhdvgeqlybWTJ2w4uQpT6e674ls36I19Gb8r/zgww6HqFscr9RdyCF+SlQQmiXSzXKeCvhjz5va5sTUlx0TlFnFBAdUEPt2/iYv/D2I4QONe6kHqFd7Snvgvacn5MwmxHCNaiPgVBCWyfPZDXWoDsFxUSIj9qpYxDHTeUrPcp6Kb/WjLeo02FtAQ+RB/AoT8TAE5V9Qp8BAxPkD+2a9tcR/b7ygcshYXzD/51gkeiwskh7yVEJjiw0ELLh5Z+ksGxftkZD6Hn+9FSJuAj8jcrIaORmXC3jztAFR+X8LZ3KiRxTguxDdxB8HuYPMpZYwW79mnzwzHl6d8uXGcypM6LTdM6jz2bqAdm27AZB2hh1e+WV3YsWyIwvponkcwSn6vGPE7YcHQ9gRoxYC2/4XfUk9yfcdX2LXL/yE+mP+P4EB6KHyQc76AVEN4EB28aCTU2lwAtVZr+dNWer0Y6zWd9TZZsMXGiN3Mx+ia2ILRkJwqG
  template:
    metadata:
      name: app-secrets
      namespace: staging
    type: Opaque
