"""
Shared error codes for the Distributed SQL Cleaner Platform.

These codes are stable identifiers used across all services.
Human-readable messages should be generated separately.
"""


class ErrorCodes:
    # Authentication
    AUTH_FAILED = "AUTH_FAILED"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"

    # Worker
    WORKER_NOT_FOUND = "WORKER_NOT_FOUND"
    WORKER_ALREADY_REGISTERED = "WORKER_ALREADY_REGISTERED"
    DUPLICATE_WORKER = "DUPLICATE_WORKER"
    WORKER_OFFLINE = "WORKER_OFFLINE"

    # Tasks
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_ALREADY_ASSIGNED = "TASK_ALREADY_ASSIGNED"
    TASK_TIMEOUT = "TASK_TIMEOUT"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED"

    # Protocol
    INVALID_MESSAGE = "INVALID_MESSAGE"
    INVALID_PROTOCOL_VERSION = "INVALID_PROTOCOL_VERSION"
    UNSUPPORTED_MESSAGE = "UNSUPPORTED_MESSAGE"

    # Coordinator
    COORDINATOR_UNAVAILABLE = "COORDINATOR_UNAVAILABLE"
    SERVER_BUSY = "SERVER_BUSY"

    # Network
    CONNECTION_LOST = "CONNECTION_LOST"
    HEARTBEAT_TIMEOUT = "HEARTBEAT_TIMEOUT"

    # Generic
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"